add ws script
ivadomed/model-csf-seg pull request #3
Opened 2024-02-05 17:06 UTC by WilliamSirois

2024-02-06 02:44 UTC, jcohenadad commented on fill-csf.py
> +        if img_fill[:,:,slice][seed[0],seed[1]]==1 : #Si mon centre de masse est sur un pixel qui vaut 1 alors je fait une fermeture
pour éviter ce scénario, tu peux aussi utiliser la segmentation de la moelle épinière pour prendre le centre de masse. Ainsi, tu es certain que le centre de masse ne sera jamais dans le CSF.

D'ailleurs, tu peux aussi utiliser la segmentation de la moelle avec la méthode de fermeture : cela te permettra de faire une fermeture beaucoup moins "aggressive" (et donc ne pas/peu modifier les bords externes de la segmentation du CSF).

2024-02-06 02:45 UTC, jcohenadad reviewed
> J'ai fait le test sur quelques images mais je ne sais pas à quel endroit les mettre pour les présenter.

Tu peux utiliser le `sct_qc` appliqué sur quelques images, puis zipper le QC folder, puis l'uploader dans cette PR pour review.

2024-02-06 22:09 UTC, WilliamSirois commented
>Tu peux utiliser le sct_qc appliqué sur quelques images, puis zipper le QC folder, puis l'uploader dans cette PR pour review.

Un peu de cette manière ou il est mieux de faire un commit pour ajouter un file?
[qc_sub-cmrrb03_canalseg_T2.zip](https://github.com/ivadomed/model-csf-seg/files/14186590/qc_sub-cmrrb03_canalseg_T2.zip)

2024-02-06 22:10 UTC, WilliamSirois commented on fill-csf.py
> +        if img_fill[:,:,slice][seed[0],seed[1]]==1 : #Si mon centre de masse est sur un pixel qui vaut 1 alors je fait une fermeture
Je vois alors je pourrais load la segmentation de la moelle puis trouver le centre de masse pour chaque slice. Ainsi je n'aurais pas à le faire pour la segmentation de la moelle puis pour celle du CSF. Je vais remplacer ça!

2024-02-07 01:44 UTC, sandrinebedard commented
> > Tu peux utiliser le sct_qc appliqué sur quelques images, puis zipper le QC folder, puis l'uploader dans cette PR pour review.
> 
> Un peu de cette manière ou il est mieux de faire un commit pour ajouter un file? [qc_sub-cmrrb03_canalseg_T2.zip](https://github.com/ivadomed/model-csf-seg/files/14186590/qc_sub-cmrrb03_canalseg_T2.zip)

Oui c'est bon comme ça! Tu pourrais aussi faire le QC juste du CSF pour comparer avec ta segmentation du canal!

2024-02-07 02:49 UTC, WilliamSirois commented on fill-csf.py
> +        if img_fill[:,:,slice][seed[0],seed[1]]==1 : #Si mon centre de masse est sur un pixel qui vaut 1 alors je fait une fermeture
J'ai remarquer que pour quelques ensembles d'image la segmentation de la moelle commence plus haut dans l'axe longitudinal et se termine plus tard. Donc plusieurs tranches n'ont pas de centre de masse pour la segmentation de la moelle. Par conséquent, si je commence par le centre de masse de la moelle pour floodfill, je risque de créer plusieurs tranches dans le haut de ma segmentation qui seront des images pleines de 1. Ainsi, je ne sais plus trop comment je peux utiliser votre conseil.

2024-02-07 03:09 UTC, jcohenadad commented on fill-csf.py
> +        if img_fill[:,:,slice][seed[0],seed[1]]==1 : #Si mon centre de masse est sur un pixel qui vaut 1 alors je fait une fermeture
> J'ai remarquer que pour quelques ensembles d'image la segmentation de la moelle commence plus haut dans l'axe longitudinal et se termine plus tard. Donc plusieurs tranches n'ont pas de centre de masse pour la segmentation de la moelle. 

ca devrait etre le contraire: si la seg de la moelle commence plus haut et finit plus bas, alors tu AS un centre de masse (via la seg de la moelle), mais il est inutile (facile à gérer: eg: si pas de CSF seg, tu ignores la slice)

2024-02-07 14:08 UTC, WilliamSirois commented on fill-csf.py
> +        if img_fill[:,:,slice][seed[0],seed[1]]==1 : #Si mon centre de masse est sur un pixel qui vaut 1 alors je fait une fermeture
>>J'ai remarquer que pour quelques ensembles d'image la segmentation de la moelle commence plus haut dans l'axe longitudinal et se termine plus tard.

>ca devrait etre le contraire: si la seg de la moelle commence plus haut et finit plus bas, alors tu AS un centre de masse (via la seg de la moelle), mais il est inutile (facile à gérer: eg: si pas de CSF seg, tu ignores la slice)

En fait je me suis trompé lorsque j'ai écrit ce commentaire la moelle commence bien plus haut mais se termine aussi plus haut il y as donc une région en bas pour laquelle j'ai un CSF mais pas de moelle. Dans cette région le centre de masse se trouve souvent sur un pixel qui vaut 1.

2024-02-08 13:22 UTC, WilliamSirois commented on fill-csf.py
> +        if img_fill[:,:,slice][seed[0],seed[1]]==1 : #Si mon centre de masse est sur un pixel qui vaut 1 alors je fait une fermeture
Parfait je vais identifier les images pour laquelle la segmentation semble incomplète et faire un issue dans la base de donnée c'est ça? J'ai donc fais comme tu m'as conseillé pour le code. Je peux donc faire un commit pour le mettre à jour?

2024-02-08 13:51 UTC, jcohenadad commented on fill-csf.py
> +        if img_fill[:,:,slice][seed[0],seed[1]]==1 : #Si mon centre de masse est sur un pixel qui vaut 1 alors je fait une fermeture
> Parfait je vais identifier les images pour laquelle la segmentation semble incomplète et faire un issue dans la base de donnée c'est ça?

👍 

> J'ai donc fais comme tu m'as conseillé pour le code. Je peux donc faire un commit pour le mettre à jour?

oui-- pas besoin de me demander à chaque fois si tu peux commit--

2024-02-09 01:12 UTC, WilliamSirois commented
Voici donc quelques images Qc créés avec le code du commit : 9438c6a43b5575cedf165c305417115c9e095471
Pour permettre de voir l'effet du code, j'ai aussi mis les images Qc de la segmentation du canal comme me l'a proposée Sandrine.
Aussi, puisque j'ai corrigé la partie du code est ce que je dois résoudre la conversation plus haut ou si c'est vous qui le ferez lorsque le code sera satisfaisant?
[qc_sub-pavia04_canalseg_T2.zip](https://github.com/ivadomed/model-csf-seg/files/14216177/qc_sub-pavia04_canalseg_T2.zip)
[qc_sub-pavia04_csfseg_T2.zip](https://github.com/ivadomed/model-csf-seg/files/14216178/qc_sub-pavia04_csfseg_T2.zip)
[qc_sub-nottwil03_canalseg_T2.zip](https://github.com/ivadomed/model-csf-seg/files/14216179/qc_sub-nottwil03_canalseg_T2.zip)
[qc_sub-nottwil03_csfseg_T2.zip](https://github.com/ivadomed/model-csf-seg/files/14216180/qc_sub-nottwil03_csfseg_T2.zip)
[qc_sub-tokyoIngenia06_canalseg_T2.zip](https://github.com/ivadomed/model-csf-seg/files/14216183/qc_sub-tokyoIngenia06_canalseg_T2.zip)
[qc_sub-tokyoIngenia06_csfseg_T2.zip](https://github.com/ivadomed/model-csf-seg/files/14216184/qc_sub-tokyoIngenia06_csfseg_T2.zip)

2024-02-09 13:37 UTC, jcohenadad commented
> Voici donc quelques images Qc créés avec le code du commit : [9438c6a](https://github.com/ivadomed/model-csf-seg/commit/9438c6a43b5575cedf165c305417115c9e095471) Pour permettre de voir l'effet du code, j'ai aussi mis les images Qc de la segmentation du canal comme me l'a proposée Sandrine. Aussi, puisque j'ai corrigé la partie du code est ce que je dois résoudre la conversation plus haut ou si c'est vous qui le ferez lorsque le code sera satisfaisant? [qc_sub-pavia04_canalseg_T2.zip](https://github.com/ivadomed/model-csf-seg/files/14216177/qc_sub-pavia04_canalseg_T2.zip) [qc_sub-pavia04_csfseg_T2.zip](https://github.com/ivadomed/model-csf-seg/files/14216178/qc_sub-pavia04_csfseg_T2.zip) [qc_sub-nottwil03_canalseg_T2.zip](https://github.com/ivadomed/model-csf-seg/files/14216179/qc_sub-nottwil03_canalseg_T2.zip) [qc_sub-nottwil03_csfseg_T2.zip](https://github.com/ivadomed/model-csf-seg/files/14216180/qc_sub-nottwil03_csfseg_T2.zip) [qc_sub-tokyoIngenia06_canalseg_T2.zip](https://github.com/ivadomed/model-csf-seg/files/14216183/qc_sub-tokyoIngenia06_canalseg_T2.zip) [qc_sub-tokyoIngenia06_csfseg_T2.zip](https://github.com/ivadomed/model-csf-seg/files/14216184/qc_sub-tokyoIngenia06_csfseg_T2.zip)

@WilliamSirois le QC peut lister plusieurs sujets-- STP génère UN SEUL QC -- ça nous évite d'avoir à telecharger/ouvrir chaque ZIP-- temps sauvé pour toi et nous--

2024-02-09 14:33 UTC, WilliamSirois commented
> @WilliamSirois le QC peut lister plusieurs sujets-- STP génère UN SEUL QC -- ça nous évite d'avoir à telecharger/ouvrir chaque ZIP-- temps sauvé pour toi et nous--

D'accord je ne savais pas que le QC pouvait avoir plusieurs sujet j'ai créer celui ci qui contient les sujets sur lesquels j'ai essayer la segmentation : 
[qc_canalseg_T2.zip](https://github.com/ivadomed/model-csf-seg/files/14222923/qc_canalseg_T2.zip)

Aussi, pour le générer j'ai roulé plusieurs fois la ligne de code sct_qc est ce qu'il y as une façon de le faire en une seule ligne pour plusieurs sujets?

2024-02-09 14:56 UTC, jcohenadad commented
> Aussi, pour le générer j'ai roulé plusieurs fois la ligne de code sct_qc est ce qu'il y as une façon de le faire en une seule ligne pour plusieurs sujets?

visionne le dernier cours: https://spinalcordtoolbox.com/user_section/courses.html

2024-02-09 16:46 UTC, sandrinebedard requested changes

2024-02-09 16:46 UTC, sandrinebedard commented on fill-csf.py
> +    Nomdecanal=csfseg.replace("csfseg-manual_RPI_r.nii","canalseg-manual_RPI_r.nii.")
je te conseille the créer un argument qui demande le nom désiré du output sinon! 

Je suis entrain de updater les noms de csf seg dans la base de données, vaut mieux ne pas hard code les noms.

Aussi les images ne doivent pas avoir le suffix `RPI_r`,  tu n'as surement pas la bonne version de la base de données, il faudrait l'updater pour être sûr d'utiliser la bonne version.

Les images doivent être enregistrées en `nii.gz` pas just `.nii`

2024-02-09 16:46 UTC, sandrinebedard commented on fill-csf.py
> +def segmentcanal(csfseg,moelleseg) :
je te conseille quand tu nommes des fonctions et arguments de suivre les recommandations de [PEP8](https://peps.python.org/pep-0008/)

surtout pour les whitespaces : https://peps.python.org/pep-0008/#whitespace-in-expressions-and-statements

2024-02-09 16:53 UTC, sandrinebedard commented
Les résultats du QC sont très bien! Pour que je puisse tester, je te conseille d'utiliser [argparse ](https://docs.python.org/3/library/argparse.html) pour ajouter des arguments pour ton script python et nous donner la commande exacte pour rouler ton code (sans hard code)!

2024-02-11 01:24 UTC, WilliamSirois commented
Le commit : f052ef8895a21247f83843cf8d6d17eefd6d25e7 
Permet de répondre aux commentaire de Sandrine au sujet de l'ajout d'arguments et de l'utilisation de PEP8. J'ai essayer au mieux d'intégrer ces recommandations et j'espère que je n'ai pas oublié de changements importants. Ensuite, pour tester l'algorithme j'ai été en mesure de la tester avec python fill-csf.py -i "Nom du fichier de segmentation du CSF" -o "Nom du fichier de sortie" -s "Nom du fichier contenant la segmentation de la moelle épinière" 
Par contre je me demandais si il est normal que pour pouvoir la tester avec WSL je doit utiliser python3?
Est ce qu'il s'agit simplement de la façon de dire à WSL d'interpréter du script python?
Voici un exemple de commande exacte pour tester le code avec les données du sujet sub-cmrrb03 tel que demandé : 
python fill-csf.py -i "sub-cmrrb03_T2w_csfseg-manual.nii.gz" -o "sub-cmrrb03_T2w_canalseg-manual.nii.gz" -s "sub-cmrrb03_T2w_seg-manual.nii.gz"

2024-02-12 18:13 UTC, jcohenadad requested changes
Add a requirements.txt file in the project

2024-02-12 18:20 UTC, jcohenadad reviewed
c'est louche :
~~~
/Users/julien/miniconda3/lib/python3.10/site-packages/scipy/ndimage/_measurements.py:1534: RuntimeWarning: invalid value encountered in scalar divide
  results = [sum(input * grids[dir].astype(float), labels, index) / normalizer
~~~

2024-02-15 01:23 UTC, WilliamSirois commented
Voici un fichier QC des images qui sont segmentées par ce code. 
Une erreur semble se produire pour l'ensemble de donnée barcelona05. Certaines tranches on vraiment un gros ajout de pixels lors de l'opération morphologique de fermeture. Je ne sais pas ce qui peut causer ce problème peut-être que le rayon du disque n'est pas approprié.
[qc_canal-seg_T2w.zip](https://github.com/ivadomed/model-csf-seg/files/14290200/qc_canal-seg_T2w.zip)

2024-02-15 02:03 UTC, jcohenadad commented
> Une erreur semble se produire pour l'ensemble de donnée barcelona05. Certaines tranches on vraiment un gros ajout de pixels lors de l'opération morphologique de fermeture. Je ne sais pas ce qui peut causer ce problème peut-être que le rayon du disque n'est pas approprié.

Bravo pour avoir produit ce QC report. C'est une bonne première étape ! Effectivement je vois le problème avec `sub-barcelona05`. Essaie de voir d'où vient le problème (eg: via le debugger).

2024-02-16 14:45 UTC, WilliamSirois commented
Après avoir modifié le rayon du disque utilisé pour le rendre plus petit et donc moins modifier les contours, je suis en mesure de bien segmenter tout en réglant le problème de `sub-barcelona05` . Voici aussi le nouveau qc_report obtenus avec le code du commit : d4a148570fbaaa4289cf89db0be0ec831cbe6c5f 
[qc_canal_seg_T2w.zip](https://github.com/ivadomed/model-csf-seg/files/14312360/qc_canal_seg_T2w.zip)

2024-02-16 22:27 UTC, sandrinebedard approved these changes
C'est super! tu pourras m'envoyer les segmentation du canal résultantes et je vais me charger de les mettre sur la base de données!

2024-02-20 15:29 UTC, sandrinebedard requested changes

2024-02-20 15:29 UTC, sandrinebedard commented on README.md
> +**Installation**
Je te conseille d'utiliser de "#" pour utiliser des headings au lieu de simplement utiliser en gras : https://www.markdownguide.org/basic-syntax/

2024-02-20 15:29 UTC, sandrinebedard commented on README.md
> +pip install -r requirements.txt
il faut premièrement git clone avant de pouvoir rouler requirements.txt (ce fichier n'est pas téléchargé encore)

2024-02-20 15:29 UTC, sandrinebedard commented on README.md
> +git clone https://github.com/ivadomed/model-csf-seg.git
Il manque `cd model-csg-seg`, 

tu peux te baser sur cet example: https://github.com/sct-pipeline/pmj-based-csa?tab=readme-ov-file#installation-1

2024-02-20 15:29 UTC, sandrinebedard commented on README.md
> +**Fonctionnement**
utiliser heading

2024-02-20 15:29 UTC, sandrinebedard commented on README.md
> +Le fait de faire la fermeture sur certaines images ne semble pas causée d'ajout de bruit à l'extérieur du CSF selon ce que j'ai observé.
Tu pourrais mettre sous forme de point de forme, ça serait plus facile à suivre!

2024-02-20 15:29 UTC, sandrinebedard commented on README.md
> +**Utilisation**
mettre heading

2024-02-20 15:29 UTC, sandrinebedard commented on README.md
> +-s Le fichier nii.gz de segmentation de la moelle épinière
```suggestion
* `-s`:  Segmentation de la moelle épinière  (.nii.gz)
```

2024-02-20 15:29 UTC, sandrinebedard commented on README.md
> +-i Le fichier nii.gz de la segmentation du csf
je mettrais -i en premier dans l'ordre et -o en dernier

2024-02-20 15:29 UTC, sandrinebedard commented on README.md
> +-i Le fichier nii.gz de la segmentation du csf
```suggestion
* `-i` :  Segmentation du CSF (.nii.gz)
```

2024-02-20 15:29 UTC, sandrinebedard commented on README.md
> +**Fonctionnement**
Tu n'a pas mis la commande à utiliser, il faudrait que tu ajoute quelque chose comme ça:

~~~
python fill-csf.py -i <CSF seg> -s <spinal cord seg> -o <output>
~~~

2024-02-20 15:29 UTC, sandrinebedard commented on requirements.txt
> +#Liste des librairies à import
```suggestion
```

2024-02-22 18:59 UTC, sandrinebedard approved these changes
les modifications du README sont okay!

2024-04-17 17:11 UTC, jcohenadad approved these changes

2024-04-17 17:11 UTC, merged